### ISSUE TITLE
Tags addon Invalid argument passed to count function

### ISSUE THREAD

**Issue by Kudratullah** [anspress/anspress#772] opened 2023-07-25 09:38 UTC
Tags addon breaks in latest PHP (7.2+) due to unsupported value passed to `count` function

```
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /opt/www/uptimemonster.com/public/wp-content/plugins/anspress-question-answer/addons/tags/tags.php:150
```

https://github.com/anspress/anspress/blob/00fd77485d5a6f1f1b895609d59f3ba9e818b9ea/addons/tags/tags.php#L145-L152

Here in `tags_page` method you already have count query which output number of tags in the query (string type int value). It can be used directly in `ceil` without passing through `count` function. 

```php
// Count terms.
$tag_args['fields'] = 'count';
$found_query        = new \WP_Term_Query( $tag_args );
$tags_rows_found    = (int) $found_query->get_terms();
$ap_max_num_pages   = ceil( $tags_rows_found / $per_page );
$question_tags      = $query->get_terms();
```

**Comment by rahularyan** [comment] 2023-07-25 09:55
Thanks @Kudratullah. This is a duplicate of #598

**Closed by rahularyan** 2023-07-25 09:55 UTC
